image: python:3.8.5

include:
  - project: 'braincube/misc/gitlabci-commons'
    file: 'gitlab-ci-send-changelog.yml'
  - project: 'braincube/misc/gitlabci-commons'
    file: 'gitlab-ci-release-notes.yml'
    ref: 'master'

default:
  before_script:
    - source $POETRY_HOME/env

stages:
  - setup
  - test
  - documentation
  - pages
  - deploy

variables:
  TEST_PYPI_REPO_URL: "https://test.pypi.org/legacy/"
  PROD_PYPI_REPO_URL: "https://upload.pypi.org/legacy/"
  POETRY_HOME: ".poetry"
  POETRY_VERSION: "1.1.4"
  APP_NAME: "braincube_connector"

setup:
  interruptible: true
  stage: setup
  before_script:
    - echo "Do not use default before_script"
  script:
    - echo $POETRY_HOME
    - mkdir $POETRY_HOME
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version $POETRY_VERSION
    - source $POETRY_HOME/env
    - poetry config virtualenvs.in-project true
    - poetry install
  artifacts:
    paths:
      - .venv
      - $POETRY_HOME
    expire_in: 60 mins

mypy:
  interruptible: true
  stage: test
  script:
    - poetry run mypy --ignore-missing-imports braincube_connector

black:
  interruptible: true
  stage: test
  script:
    - poetry run black --check --diff .

lint:
  interruptible: true
  stage: test
  script:
    - poetry run flake8 braincube_connector

unittest:
  interruptible: true
  stage: test
  script:
    - poetry run coverage run --source=braincube_connector -m pytest tests/*
    - poetry run coverage report
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then poetry run coverage html; fi
  artifacts:
    paths:
      - htmlcov
    expire_in: 60 mins

integration_tests:
  interruptible: true
  stage: test
  script:
    - poetry run pytest tests_integration/*.py

documentation:
  stage: documentation
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ipleanware.com/braincube/misc/gitlabci-commons.git
    - cp -r gitlabci-commons/braincube-pages/docs/* docs
    - cp -r gitlabci-commons/braincube-pages/custom_theme .
    - bash docs/build_doc.sh build
  artifacts:
    paths:
      - site
      - badge_doc.svg
    expire_in: 60 mins
  only:
      - master

pages:
  stage: pages
  script:
    - mkdir public
    - mkdir public/badges
    - cp badge*.svg public/badges
    - cp -r site public/
    - cp -r htmlcov public/
  artifacts:
    paths:
      - public
  only:
      - master

testpypi:
  stage: deploy
  script:
    - poetry build
    - poetry config repositories.test $TEST_PYPI_REPO_URL
    - poetry publish -r test -u $PYPI_STAGING_USERNAME -p $PYPI_STAGING_PASSWORD
  only:
    - master
  when: manual

pypi:
  stage: deploy
  script:
    - poetry build
    - poetry config repositories.prod $PROD_PYPI_REPO_URL
    - poetry publish -r prod -u $PYPI_PROD_USERNAME -p $PYPI_PROD_PASSWORD
  only:
    - tags

new_release_note:
  extends: .create-release-note

deploy_release_note:
  extends: .publish-release-note

notification:
  extends: .send_changelog
