image: renovate/poetry

include:
  - project: 'braincube/misc/gitlabci-commons'
    file: 'gitlab-ci-send-changelog.yml'

stages:
  - setup
  - test
  - documentation
  - pages
  - publish

variables:
  TEST_PYPI_REPO_URL: "https://test.pypi.org/legacy/"
  PROD_PYPI_REPO_URL: "https://upload.pypi.org/legacy/"

setup:
  stage: setup
  script:
    - poetry config virtualenvs.in-project true
    - poetry install
  artifacts:
    paths:
      - .venv/
    expire_in: 60 mins

mypy:
  stage: test
  script:
    - poetry run mypy braincube_connector

black:
  stage: test
  script:
    - poetry run black --check --diff braincube_connector tests

lint:
  stage: test
  script:
    - poetry run flake8 braincube_connector

unittest:
  stage: test
  script:
    - poetry run coverage run --source=braincube_connector -m pytest tests/*
    - poetry run coverage report
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then poetry run coverage html; fi
  artifacts:
    paths:
      - htmlcov
    expire_in: 60 mins

documentation:
  stage: documentation
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ipleanware.com/braincube/misc/gitlabci-commons.git
    - cp -r gitlabci-commons/braincube-pages/docs/* docs
    - cp -r gitlabci-commons/braincube-pages/custom_theme .
    - bash docs/build_doc.sh build
  artifacts:
    paths:
      - site
      - badge_doc.svg
    expire_in: 60 mins
  only:
      - master

pages:
  stage: pages
  script:
    - mkdir public
    - mkdir public/badges
    - cp badge*.svg public/badges
    - cp -r site public/
    - cp -r htmlcov public/
  artifacts:
    paths:
      - public
  only:
      - master

testpypi:
  stage: publish
  script:
    - poetry build
    - poetry config repositories.test $TEST_PYPI_REPO_URL
    - poetry publish -r test -u $PYPI_STAGING_USERNAME -p $PYPI_STAGING_PASSWORD
  only:
    - master
  when: manual

pypi:
  stage: publish
  script:
    - poetry build
    - poetry config repositories.prod $PROD_PYPI_REPO_URL
    - poetry publish -r prod -u $PYPI_PROD_USERNAME -p $PYPI_PROD_PASSWORD
  only:
    - tags

notification:
  stage: publish
  extends: .send_changelog
