site_name: 'braincube_connector'
repo_url: 'https://gitlab.ipleanware.com/braincube/core/python/braincube_connector'
site_url: 'https://braincube.pages.ipleanware.com/core/python/braincube_connector/site/'
theme: 
  name: 'material'
  custom_dir: 'custom_theme'
  favicon: 'images/favicon.ico'
extra_css:
  - 'extra.css'
extra:
  logo: 'images/braincube.png'
  search:
    language: 'en, fr'
markdown_extensions:
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Usage: usage.md
  - Documentation: documentation.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings
